name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest 
    
    steps:
    - uses: actions/checkout@v2
    - name: pre
      run: sudo apt-get install tree
    - name: make1
      run: cd $GITHUB_WORKSPACE && ls && tree

