name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: windows-latest 
    
    steps:
    - uses: actions/checkout@v2
    - name: make1
      run: g++ Hash_obfs.cpp
    - name: make2
      run: gcc Download_video.c
