name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: windows-latest 
    
    steps:
    - uses: actions/checkout@v2
    - name: install_mingw
      run: choco install mingw
    - name: make1
      run: gcc Download_video.c -o Download_video.exe
    - name: make2
      run: g++ Hash_obfs.cpp -o Hash_obfs.exe
